version: 0.2
phases:
  install:
    runtime-versions:
      python: 3.7
  pre_build:
    commands:
      - wget https://binaries.sonarsource.com/Distribution/sonar-scanner-cli/sonar-scanner-cli-4.7.0.2747-linux.zip
      - unzip ./sonar-scanner-cli-4.7.0.2747-linux.zip
      - export PATH=$PATH:./sonar-scanner-4.7.0.2747-linux/bin/
  build:
    commands:
      - sonar-scanner -Dsonar.login=40e4aa48b2df8eb23fe1fe3cf0c8236e8a3ca62c -Dsonar.host.url=https://sonarcloud.io -Dsonar.projectKey=devopsecisha6 -Dsonar.organization=devosecisha6 -DgeneratePom=true
      - sleep 5
      - curl https://sonarcloud.io/api/qualitygates/project_status?projectKey=devopsecisha6 >result.json
      - cat result.json
      - if [ $(jq -r '.projectStatus.status' result.json) = ERROR ] ; then $CODEBUILD_BUILD_SUCCEEDING -eq 0 ;fi